services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
      target: dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "9090:9090"
      - "5005:5005"
    volumes:
      - ./auth-service:/app/auth-service
    command: >
      ./mvnw spring-boot:run
      -Dspring-boot.run.profiles=dev
      -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      target: dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "9091:9091"
      - "5006:5006"
    volumes:
      - ./user-service:/app/user-service
    command: >
      ./mvnw spring-boot:run
      -Dspring-boot.run.profiles=dev
      -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"

